# Generated by Django 2.0 on 2019-06-13 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=' ', max_length=256, null=True)),
                ('phone', models.CharField(blank=True, default=0, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(blank=True, max_length=40, null=True)),
                ('name', models.CharField(blank=True, default=' ', max_length=256, null=True)),
                ('phone', models.CharField(blank=True, default=0, max_length=40, null=True)),
                ('address', models.CharField(blank=True, max_length=40, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_branch', to='main.Branch')),
            ],
        ),
        migrations.AddField(
            model_name='reading',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reading_customer', to='main.Customer'),
        ),
        migrations.AddField(
            model_name='reading',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reading_device', to='main.Device'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='device',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_customer', to='main.Customer'),
        ),
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_location', to='main.Location'),
        ),
        migrations.AlterField(
            model_name='reading',
            name='post_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='location',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_customer', to='main.Customer'),
        ),
        migrations.AddField(
            model_name='branch',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_customer', to='main.Customer'),
        ),
    ]
