# Generated by Django 2.0 on 2019-07-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190701_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='post_date',
            field=models.DateField(blank=True),
        ),
    ]
