# Generated by Django 2.0 on 2019-07-07 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_reading_post_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reading_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reading',
            name='post_datetime',
            field=models.DateTimeField(blank=True),
        ),
    ]
