# Generated by Django 2.0 on 2019-08-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_branch_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
