# Generated by Django 2.0 on 2019-09-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_device_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_day_energy',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_day_energy_post_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
