# Generated by Django 2.0 on 2019-10-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_customer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField(blank=True, max_length=2000)),
                ('document', models.FileField(blank=True, default=None, null=True, upload_to='message_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_new_message', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='customer_imgs/'),
        ),
        migrations.AddField(
            model_name='thread',
            name='reciever',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='thread_reciever', to='main.Customer'),
        ),
        migrations.AddField(
            model_name='thread',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thread_sender', to='main.Customer'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Thread'),
        ),
    ]
