# Generated by Django 2.0 on 2019-10-30 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20191030_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='sender',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='reciever',
            new_name='guest',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='sender',
            new_name='host',
        ),
    ]
