# Generated by Django 2.0 on 2019-10-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20191030_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='is_new_message',
            new_name='has_new_message',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
        migrations.AddField(
            model_name='message',
            name='has_been_read',
            field=models.BooleanField(default=False),
        ),
    ]
