# Generated by Django 2.0 on 2019-11-01 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20191031_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='message_receiver', to='main.Customer'),
        ),
    ]
