# Generated by Django 2.0 on 2019-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20191101_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='gen1_val',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='gen2_val',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
