# Generated by Django 2.0 on 2019-11-08 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20191101_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Degree_Days',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('value', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
