# Generated by Django 2.0 on 2019-11-08 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_degree_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Degree_Days',
            new_name='Degree_Day',
        ),
    ]
