# Generated by Django 2.0 on 2019-11-11 09:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0021_auto_20191108_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datalogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_datetime', models.DateTimeField(blank=True)),
                ('post_date', models.DateField(blank=True)),
                ('post_time', models.TimeField(blank=True)),
                ('digital_input_1', models.FloatField(blank=True, default=None, null=True)),
                ('digital_input_2', models.FloatField(blank=True, default=None, null=True)),
                ('digital_input_3', models.FloatField(blank=True, default=None, null=True)),
                ('digital_input_4', models.FloatField(blank=True, default=None, null=True)),
                ('summary_energy_register_1', models.FloatField(blank=True, default=None, null=True)),
                ('summary_energy_register_2', models.FloatField(blank=True, default=None, null=True)),
                ('total_kw', models.FloatField(blank=True, default=None, null=True)),
                ('customer', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Customer')),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Device')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
