# Generated by Django 2.0 on 2019-11-11 10:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0022_datalogs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Datalogs',
            new_name='Datalog',
        ),
    ]
