# Generated by Django 2.0 on 2019-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20191111_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalog',
            name='pulse_counter',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
