# Generated by Django 2.0 on 2019-11-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_datalog_pulse_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_main_admin',
            field=models.BooleanField(default=True),
        ),
    ]
