# Generated by Django 2.0 on 2019-12-14 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_customer_is_main_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='scores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(blank=True, null=True)),
                ('felf', models.FloatField(blank=True, default=0, null=True)),
                ('avg_load', models.FloatField(blank=True, default=0, null=True)),
                ('peak_load', models.FloatField(blank=True, default=0, null=True)),
                ('capacity_factor_gen1', models.FloatField(blank=True, default=0, null=True)),
                ('capacity_factor_gen2', models.FloatField(blank=True, default=0, null=True)),
                ('fuel_consumption_gen1', models.FloatField(blank=True, default=0, null=True)),
                ('fuel_consumption_gen2', models.FloatField(blank=True, default=0, null=True)),
                ('baseline_energy', models.FloatField(blank=True, default=0, null=True)),
                ('energy_used', models.FloatField(blank=True, default=0, null=True)),
                ('device', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Device')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='is_main_admin',
            field=models.BooleanField(default=False),
        ),
    ]
