# Generated by Django 2.0 on 2019-12-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20191214_2250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='scores',
            new_name='Score',
        ),
    ]
