# Generated by Django 2.0 on 2019-12-14 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20191214_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='month',
            new_name='date',
        ),
    ]
