# Generated by Django 2.0 on 2019-12-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20191214_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='hours_gen1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='hours_gen2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
