# Generated by Django 2.0 on 2019-12-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20191215_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='added',
            field=models.DateField(auto_now=True),
        ),
    ]
