# Generated by Django 2.0 on 2019-12-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_customer_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='added',
            field=models.DateField(auto_now=True),
        ),
    ]
