# Generated by Django 2.0 on 2019-12-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20191223_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='gen1_kwh',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='gen2_kwh',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='utility_kwh',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_load_balance_check',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
